apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: randserver-data
  namespace: kube-logging 
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: slow
  resources:
    requests:
      storage: 30Gi